import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState } from 'react';
import { PuffLoader } from "react-spinners";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [title,setTitle] = useState('');
  const [description,setDescription] = useState('');
  const [loading,setLoading] = useState(false);
  const [dataFound,setDataFound] = useState(null);

  const getData = async ()=>{
    setLoading(true);
    console.log('button clicked');
    console.log('description'  +description);
  
    let dataToSend = {
      title:title,
      description:description
    }
    console.log(dataToSend);
    let response = await fetch('/api/getdata',{
      method:'POST',
      headers:{
        'Content-Type':'application/json',
      },
      body: JSON.stringify(dataToSend)
    });
    if(response.ok){
      const data = await response.json();
      console.log(data.message);
      setLoading(false);
      setDataFound(data.message);
    }
  }

  const onChangeTitle = (event)=>{
    setTitle(event.target.value);
    console.log(event.target.value);
  }

  const onChangeDescription = (event)=>{
    setDescription(event.target.value);
    console.log(event.target.value);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.page}>
          <h1 className={styles.header}>Build Websites in seconds ✨</h1>
            <div className={styles.center_div}>
                {loading ? <PuffLoader/> : 
                  <>
                    {dataFound !== null ?
                         <div>
                            <h1 style={{color:'black'}}>Download NGO Data</h1>
                            <a href="/ngo.json" download="ngo.json">
                                Download ngo.json
                            </a>
                          </div>
                  
                      :
                          <>
                              <div className={styles.title_div}>
                                <p className={styles.center_div_title}>Title</p>
                                <input className={styles.title_input} onChange={onChangeTitle} placeholder="non-profit name" value={title}/>
                              </div>

                              <div className={styles.description_div}>
                                  <p className={styles.center_div_title}>Description</p>
                                  <input className={styles.description_input} onChange={onChangeDescription} value={description} placeholder='enter description'/>
                              </div>

                              <button className={styles.generate_div} onClick={getData}>
                                  <p className={styles.generate_div_title}>Generate</p>
                              </button>
                          </>
                      }
                  </>
              }
            </div>
        </div>  
    </>
  );
}
